# -*- coding: utf-8 -*-

import os
from abc import ABCMeta, abstractmethod
from aiida.orm.repository import Repository

class RepositorySwift(Repository):
    """
    """
    __metaclass__ = ABCMeta

    def __init__(self, repo_config):
        """
        :param repo_config: dictionary with configuration details for repository
        """
        raise NotImplementedError

    def get_uuid(self):
        """
        Return the UUID identifying the repository.
        Each implementation will decide how to store it: 
        e.g. in a FS it could be a file repo_uuid.txt in the main folder,
        in a object store it could be stored under a key name 'repo_uuid' (making
        sure no object can be stored with the same name) etc.
        """
        raise NotImplementedError

    def put_object(self, key, content, stop_if_existing=False):
        """
        Add the object to the repository with the specified content if 
        it does not exist. Overwrite if exists and stop_if_existing is False.
        Raise an exception if stop_if_existing is True and the object already exists.

        :param key: fully qualified identifier for the object within the repository
        :param content: file or filelike
        :param stop_if_existing:
        """
        raise NotImplementedError

    def put_new_object(self, content, node_uuid, relpath):
        """
        Add the object to the repository with some autogenerated name.
        Can (optionally) use the information from node_uuid (string) and relpath (string),
        but it is not needed.
        Must return the key used to store the object.
        It never overwrites existing data. If you want to overwrite an existing object,
        call put_object passing the correct key.

        :return: the key of the newly generated object
        """
        raise NotImplementedError

    def exists(self, key):
        """
        Determine whether the file identified by key exists and is readable

        :return boolean: returns True if the file exists and is readable, False otherwise
        In swift, use head_object() and catch 404 exception.
        """
        raise NotImplementedError

    def get_object(self, key):
        """
        Get the content
        """
        raise NotImplementedError

    def del_object(self, key):
        """
        Delete the object. This class is still valid, if you put again you recreate the object.
        """
        raise NotImplementedError